name:
description:   Standards for developing flexible, durable, and sustainable HTML and CSS, and maintainable JavaScript
url:           https://github.com/xianglongxiang/CodeGuide

include:       [".editorconfig", ".jscsrc", ".jshintrc", ".csslintrc", ".scss-lint.yml"]

markdown:      rdiscount
permalink:     pretty
pygments:      true
